---
title: "Analysis Template 4"
format: html
---

Document to test out the "Functions.R" file and see how the estimators perform.

# Packages

```{r}
library(tidyverse)
library(dsims)
library(Distance)
library(dssd)
library(dsm)
library(sf)
library(mgcv)
library(qrng) 
```

# Import Functions

```{r}
source(here::here("Functions4.R"))
```

# Constants

```{r}
true_N <- 10000

points_or_lines = "line"

trunc_dist <- 30
scale_parameter <- 15
design_spacing <- 500

density_grid_spacing <- 100

design_angle <- 0
bootstrap_reps <- 10
```

# Code

## Region

```{r}
region <- make_region(region_sf = NULL, 0, 5000, 0, 5000, "m")
```

## Density

```{r}
# my_hotspots <- list(
#   list(centre = c(2000, 8000), sigma = 800, amplitude = 1.2),
#   list(centre = c(5000, 2000), sigma = 6000, amplitude = 0.5),
#   list(centre = c(8000, 9000), sigma = 1000, amplitude = 2)
# )

my_hotspots <- list(
  list(centre = c(2500, 2500), sigma = 8000, amplitude = 0.1)
)

density_true <- make_hotspot_density(region, my_hotspots)
```

## True population

```{r}
sim_pop <- generate_simulated_pop(region,
                                  density_true)

# FIX: Map these to the exact names exported by the list in get_simulated_pop()
density <- sim_pop$density
population_description <- sim_pop$population_description
population <- sim_pop$population
detectability <- sim_pop$detectability
```

## Survey

generates the iteration of survey data analogous to real data collection

```{r}
survey_data_lines <- survey_data(
  region = region,
  realized_population = sim_pop$population,
  transect_type = points_or_lines
)

design <- survey_data_lines$design
transects <- survey_data_lines$transects
samplers <- transects@samplers
dist_data <- survey_data_lines$dist_data
obs_data <- survey_data_lines$obsdata
seg_data <- survey_data_lines$segdata
```

## ds() Fit 

```{r}
ds_results <- fit_ds(
  region = region,
  dist_data = survey_data_lines$dist_data,
  obsdata = obs_data,
  segdata = seg_data,
  transect_type = points_or_lines,
  truncation = trunc_dist
)
```

## dsm() models

```{r}
dsm_results <- fit_dsm_and_surface(
  obsdata = obs_data,
  segdata = seg_data,
  ds_model = ds_results$ds_model,
  region = region,
  N_hat = ds_results$N_hat,
  transect_type = points_or_lines,
  x_space = density_grid_spacing,
  y_space = density_grid_spacing
)
```

## Striplet/Boxlet

```{r}
striplet_boxlet <- striplet_boxlet(region = region,
                                   segdata = seg_data,
                                   dsm_model = dsm_results$dsm_model,
                                   dsm_surface = dsm_results$dsm_surface,
                                   ds_results = ds_results,
                                   transect_type = points_or_lines,
                                   spacing = design_spacing,
                                   truncation = trunc_dist)
```

## Bootstraps

```{r}
standard <- get_bootstrap(region = region,
                          population_description = dsm_results$population_description,
                          sigma_hat = ds_results$sigma_hat,
                          transect_type = points_or_lines,
                          reps = bootstrap_reps,
                          # angle = design_angle,
                          spacing = design_spacing,
                          truncation = trunc_dist
)

sd(standard$N_hat, na.rm = TRUE)
```

```{r}
# invcdf <- get_bootstrap_invcdf(
#   region = region,
#   population_description = dsm_results$population_description,
#   sigma_hat = ds_results$sigma_hat,
#   transect_type = points_or_lines,
#   reps = bootstrap_reps,
#   angle = design_angle,
#   spacing = design_spacing,
#   truncation = trunc_dist
# )
# 
# # invcdf <- invcdf |>
# #   arrange(N_hat) |>
# #   slice(1:91)
# 
# sd(invcdf$N_hat, na.rm = TRUE)
```

```{r}
disc_density <- get_bootstrap_disc_density(region = region,
                                           population_description = dsm_results$population_description,
                                           sigma_hat = ds_results$sigma_hat,
                                           transect_type = points_or_lines,
                                           reps = bootstrap_reps,
                                           # angle = design_angle,
                                           spacing = design_spacing,
                                           truncation = trunc_dist
)

sd(disc_density$N_hat, na.rm = TRUE)
```



