---
title: "testing_functions"
format: html
---

Document to test out the "Functions.R" file and see how the estimators perform.

# Packages

```{r}
library(tidyverse)
library(dsims)
library(Distance)
library(dssd)
library(dsm)
library(sf)
library(mgcv)
library(qrng) 
```

# Import Functions

```{r}
source(here::here("Functions.R"))
```

# Constants

```{r}
true_N <- 5000

points_or_lines = "line"

trunc_dist <- 750
scale_parameter <- 200
design_spacing <- 750

density_grid_spacing <- 500

design_angle <- 0
bootstrap_reps <- 100
```

# Code

## Region

```{r}
region <- make_region(region_sf = NULL, 0, 10000, 0, 10000, "m")
```

## Density

```{r}
my_hotspots <- list(
  list(centre = c(2000, 8000), sigma = 800, amplitude = 1.2),
  list(centre = c(5000, 2000), sigma = 6000, amplitude = 0.5),
  list(centre = c(8000, 9000), sigma = 1000, amplitude = 2)
)

density_true <- make_hotspot_density(region, my_hotspots)
```

## True population

```{r}
sim_pop<- generate_simulated_pop(region)

# FIX: Map these to the exact names exported by the list in get_simulated_pop()
density <- sim_pop$density
population_description <- sim_pop$population_description
population <- sim_pop$population
detectability <- sim_pop$detectability
```

## Survey

generates the iteration of survey data analogous to real data collection

```{r}
survey_data_lines <- generate_survey_data(
  region = region,
  realized_population = sim_pop$population,
  transect_type = points_or_lines
)

design <- survey_data_lines$design
transects <- survey_data_lines$transects
samplers <- transects@samplers
```

## Fit 

```{r}
fit_lines <- get_fit(
  dist_data = survey_data_lines$dist_data,
  transects = survey_data_lines$transects,
  region = region,
  transect_type = points_or_lines
)

obs_data <- fit_lines$obsdata
seg_data <- fit_lines$segdata
dsm1 <- fit_lines$dsm
density_surface <- fit_lines$density_surface
```

## Bootstraps

```{r}
standard <- get_bootstrap(
  region = region,
  population_description = fit_lines$population_description,
  sigma_hat = fit_lines$sigma_hat,
  transect_type = points_or_lines,
  reps = bootstrap_reps
)

sd(standard$N_hat)
```

```{r}
invcdf <- get_bootstrap_invcdf(
  region = region,
  population_description = fit_lines$population_description,
  sigma_hat = fit_lines$sigma_hat,
  transect_type = points_or_lines,
  reps = bootstrap_reps
)

# invcdf <- invcdf |>
#   arrange(N_hat) |>
#   slice(1:91)

sd(invcdf$N_hat)
```

```{r}
disc_density <- get_bootstrap_disc_density(
  region = region,
  population_description = fit_lines$population_description,
  sigma_hat = fit_lines$sigma_hat,
  transect_type = points_or_lines,
  reps = bootstrap_reps
)

sd(disc_density$N_hat)
```



